stages:
  - test
  - build

include:
  - project: SEDA.digital/modx-environment
    ref: main
    file: .gitlab-ci.template.yml

build:transport:
  extends: .build-transport
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
