stages:
  - test
  - build

include:
  - project: SEDA.digital/modx-environment
    ref: main
    file: .gitlab-ci.template.yml

build:transport:
  extends: .build-transport
  stage: build
  artifacts:
    paths:
      - "modx-environment/components/${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}/_build/_packages/*.transport.zip"
    #expire_in: 1 day
